version: "3"
services:
  front:
    image: lojaspringfront
    ports:
      - "3000:80"
    depends_on:
      - back
  back:
    image: lojaspringback
    environment:
      - MYSQL_HOST=mysqlbd
    ports:
      - "8080:8080"
    depends_on:
      - mysqlbd
  mysqlbd:
    image: lojaspringbd
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=true
